---

#
# set up a jenkins worker -- muy bueno!
#

- hosts:
  - test
  - release
  - "!test-joyent-freebsd10-x64-2"
  - "!test-rackspace-freebsd10-x64-1"

  vars_prompt:
    - name: "FTP3USER"
      prompt: "Enter w3 username"
      private: no
    - name: "FTP3PASS"
      prompt: "Enter w3 password"
      private: yes

  roles:
    - bootstrap
    - package-upgrade
    - baselayout
    - jenkins-worker

  pre_tasks:
    - name: check if secret is properly set
      fail:
      failed_when: not secret

  environment:
    FTP3USER: "{{ FTP3USER }}"
    FTP3PASS: "{{ FTP3PASS }}"
    become: true
